Fix nosetests breakage
The last commit broke nosetests:

File "__init__.py",
line 7, in <module>
    del sys.modules['httplib2']
KeyError: 'httplib2'

Change-Id: Iff36327735b9e535bda2968ac17032efdaf76d24